 #docker-compose.override.yml
 # Lista todos os Serviços do Docker
services:
  # Serviço do banco de dados PostgreSQL
  database:
    build:
      # Define o caminho onde o Dockerfile está localizado para construir a imagem
      context: ./img_postgres
      # Especifica o Dockerfile a ser utilizado para a construção da imagem
      dockerfile: Dockerfile

  # Serviço do License Server
  licenseserver:
    build:
      # Define o diretório onde o Dockerfile está localizado para a construção da imagem
      context: ./img_license
      # Especifica o Dockerfile a ser utilizado para a construção da imagem
      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  # Serviço do Dbaccess
  dbaccess:
    build:
      # Define o diretório onde o Dockerfile está localizado para a construção da imagem
      context: ./img_dbaccess
      # Especifica o Dockerfile a ser utilizado para a construção da imagem
      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  # Serviço do Protheus (contém componentes como appserver, rest etc.)
  protheus:
    build:
      # Define o caminho para o diretório onde o Dockerfile do Protheus está localizado
      context: ./img_protheus
      # Especifica o Dockerfile a ser utilizado para a construção da imagem
      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  # Serviço do SmartView 
  smartview:
    build:
      # Define o caminho para o diretório onde o Dockerfile do SmartView está localizado
      context: ./img_smartview
      # Especifica o Dockerfile a ser utilizado para a construção da imagem
      dockerfile: Dockerfile
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
